POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjViZjlhMGQyZGFlZjMwM2IxMGYzNTZlMiIsImlhdCI6MTU0Mzc2MjcyOH0.81kmVT0RSsgYGNEmTDCQUzQz02B7XE4meDXmas0fmvM

{
    "_id": "5a422a851b54a676234d17f7",
    "title": "React patterns",
    "author": "Michael Chan",
    "url": "https://reactpatterns.com/",
    "likes": 7,
    "__v": 0
}